### ISSUE TITLE
font问题

### ISSUE THREAD

**Issue by Neilsons** [soul-soft/Soul.PDFsharp.Extensions#1]
您好，想咨询您一下，关于字体的问题，我这边使用字体嵌入的方式，嵌入了黑体和宋体，然后在window上部署是导出pdf是正常的，在linux物理机上部署导出也正常，使用docker部署导出的pdf中文变为了方框，想问下这个是编码的问题还是其他的问题呢，非常感谢您。

**Comment by soul-soft** [comment]
1. 首先确定，在docker容器中，是否存在该字体，并成功加载字体
2. 确定编写pdf相关的源码文件采用的是UTF-8无签名-代码页65001（vs下文件另存为->保存下三角->编码保存）
3. 本库算法上存在一定的问题，只是我项目中需要用到布局，简单的实现了一下Grid布局算法，建议在我的数据结构下，基于AI或者手动完善它。

**Comment by Neilsons** [comment]
非常感谢您，我这边生成pdf的文件是GB2312-代码页936，改为UTF-8无签名-代码也65001后可以正常导出。

**Comment by soul-soft** [comment]
> 非常感谢您，我这边生成pdf的文件是GB2312-代码页936，改为UTF-8无签名-代码也65001后可以正常导出。

OK！我研发的这个布局算法，今天也已经修复掉了单元格的外边距问题！

**Comment by Neilsons** [comment]
嗯嗯，及时关注您，我这边生成表格的不能自动换行，我就搁几个字符自己添加换行符，然后我看这个chart支持好几种类型，也有饼状图的枚举，但是目前不支持。

**Comment by soul-soft** [comment]
> 嗯嗯，及时关注您，我这边生成表格的不能自动换行，我就搁几个字符自己添加换行符，然后我看这个chart支持好几种类型，也有饼状图的枚举，但是目前不支持。

PdfSharp不是我开发，我只是在这上面加了Grid布局。PdfSharp貌似不支持布局。它只提供了XGraphics绘制方案。我给他写了一个Grid布局，可以减少像素坐标位置的计算。实现类似前端的Grid布局思维。

我写的这个，目前支持文本自动换行，水平垂直方向对齐，内外边距等算法。

**Comment by Neilsons** [comment]
支持支持。。。
